2016-05-05 14:53:30 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ð�ÐµÐ´Ð¾Ð¿ÑƒÑ�Ñ‚Ð¸Ð¼Ð¾Ðµ Ð·Ð½Ð°Ñ‡ÐµÐ½Ð¸Ðµ "1" Ð´Ð»Ñ� Ð¿Ð°Ñ€Ð°Ð¼ÐµÑ‚Ñ€Ð° "parameterIndex"
Invalid value "1" for parameter "parameterIndex" [90008-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:228)
	at org.h2.jdbc.JdbcPreparedStatement.setParameter(JdbcPreparedStatement.java:1406)
	at org.h2.jdbc.JdbcPreparedStatement.setString(JdbcPreparedStatement.java:355)
	at homeworks.task1.Functionality.insert(WorkWithTable.java:48)
	at homeworks.task1.Main.main(Main.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
2016-05-05 20:25:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Savepoint Ð½Ðµ Ñ�ÑƒÑ‰ÐµÑ�Ñ‚Ð²ÑƒÐµÑ‚: "SYSTEM_SAVEPOINT_0"
Savepoint is invalid: "SYSTEM_SAVEPOINT_0"; SQL statement:
ROLLBACK TO SAVEPOINT SYSTEM_SAVEPOINT_0 [90063-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.engine.Session.rollbackToSavepoint(Session.java:1051)
	at org.h2.command.dml.TransactionCommand.update(TransactionCommand.java:59)
	at org.h2.command.CommandContainer.update(CommandContainer.java:98)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcSavepoint.rollback(JdbcSavepoint.java:66)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:1037)
	at homeworks.task1.Functionality.insert(WorkWithTable.java:60)
	at homeworks.task1.Main.main(Main.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
2016-05-05 21:05:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ð”Ð°Ð½Ð½Ñ‹Ð¹ Ð¼ÐµÑ‚Ð¾Ð´ Ð½Ðµ Ñ€Ð°Ð·Ñ€ÐµÑˆÐµÐ½ Ð´Ð»Ñ� PreparedStatement; Ð¸Ñ�Ð¿Ð¾Ð»ÑŒÐ·ÑƒÐ¹Ñ‚Ðµ Statement.
This method is not allowed for a prepared statement; use a regular statement instead. [90130-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:295)
	at homeworks.task1.Functionality.delete(WorkWithTable.java:85)
	at homeworks.task1.Main.main(Main.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
2016-05-05 21:07:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ð”Ð°Ð½Ð½Ñ‹Ð¹ Ð¼ÐµÑ‚Ð¾Ð´ Ð½Ðµ Ñ€Ð°Ð·Ñ€ÐµÑˆÐµÐ½ Ð´Ð»Ñ� PreparedStatement; Ð¸Ñ�Ð¿Ð¾Ð»ÑŒÐ·ÑƒÐ¹Ñ‚Ðµ Statement.
This method is not allowed for a prepared statement; use a regular statement instead. [90130-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:279)
	at homeworks.task1.Functionality.delete(WorkWithTable.java:85)
	at homeworks.task1.Main.main(Main.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
2016-05-05 21:09:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ð”Ð°Ð½Ð½Ñ‹Ð¹ Ð¼ÐµÑ‚Ð¾Ð´ Ð½Ðµ Ñ€Ð°Ð·Ñ€ÐµÑˆÐµÐ½ Ð´Ð»Ñ� PreparedStatement; Ð¸Ñ�Ð¿Ð¾Ð»ÑŒÐ·ÑƒÐ¹Ñ‚Ðµ Statement.
This method is not allowed for a prepared statement; use a regular statement instead. [90130-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:279)
	at homeworks.task1.Functionality.delete(WorkWithTable.java:85)
	at homeworks.task1.Main.main(Main.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
2016-05-05 21:11:16 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ð”Ð°Ð½Ð½Ñ‹Ð¹ Ð¼ÐµÑ‚Ð¾Ð´ Ð½Ðµ Ñ€Ð°Ð·Ñ€ÐµÑˆÐµÐ½ Ð´Ð»Ñ� PreparedStatement; Ð¸Ñ�Ð¿Ð¾Ð»ÑŒÐ·ÑƒÐ¹Ñ‚Ðµ Statement.
This method is not allowed for a prepared statement; use a regular statement instead. [90130-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:279)
	at homeworks.task1.Functionality.delete(WorkWithTable.java:86)
	at homeworks.task1.Main.main(Main.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
2016-05-05 21:13:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ð”Ð°Ð½Ð½Ñ‹Ð¹ Ð¼ÐµÑ‚Ð¾Ð´ Ð½Ðµ Ñ€Ð°Ð·Ñ€ÐµÑˆÐµÐ½ Ð´Ð»Ñ� PreparedStatement; Ð¸Ñ�Ð¿Ð¾Ð»ÑŒÐ·ÑƒÐ¹Ñ‚Ðµ Statement.
This method is not allowed for a prepared statement; use a regular statement instead. [90130-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:279)
	at homeworks.task1.Functionality.delete(WorkWithTable.java:86)
	at homeworks.task1.Main.main(Main.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
2016-05-05 21:14:27 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ð”Ð°Ð½Ð½Ñ‹Ð¹ Ð¼ÐµÑ‚Ð¾Ð´ Ð½Ðµ Ñ€Ð°Ð·Ñ€ÐµÑˆÐµÐ½ Ð´Ð»Ñ� PreparedStatement; Ð¸Ñ�Ð¿Ð¾Ð»ÑŒÐ·ÑƒÐ¹Ñ‚Ðµ Statement.
This method is not allowed for a prepared statement; use a regular statement instead. [90130-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:279)
	at homeworks.task1.Functionality.delete(WorkWithTable.java:86)
	at homeworks.task1.Main.main(Main.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
2016-05-05 21:15:09 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ð”Ð°Ð½Ð½Ñ‹Ð¹ Ð¼ÐµÑ‚Ð¾Ð´ Ð½Ðµ Ñ€Ð°Ð·Ñ€ÐµÑˆÐµÐ½ Ð´Ð»Ñ� PreparedStatement; Ð¸Ñ�Ð¿Ð¾Ð»ÑŒÐ·ÑƒÐ¹Ñ‚Ðµ Statement.
This method is not allowed for a prepared statement; use a regular statement instead. [90130-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:295)
	at homeworks.task1.Functionality.delete(WorkWithTable.java:86)
	at homeworks.task1.Main.main(Main.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
2016-05-05 21:16:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ð”Ð°Ð½Ð½Ñ‹Ð¹ Ð¼ÐµÑ‚Ð¾Ð´ Ð½Ðµ Ñ€Ð°Ð·Ñ€ÐµÑˆÐµÐ½ Ð´Ð»Ñ� PreparedStatement; Ð¸Ñ�Ð¿Ð¾Ð»ÑŒÐ·ÑƒÐ¹Ñ‚Ðµ Statement.
This method is not allowed for a prepared statement; use a regular statement instead. [90130-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:279)
	at homeworks.task1.Functionality.delete(WorkWithTable.java:86)
	at homeworks.task1.Main.main(Main.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
2016-05-05 21:18:59 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ð”Ð°Ð½Ð½Ñ‹Ð¹ Ð¼ÐµÑ‚Ð¾Ð´ Ð½Ðµ Ñ€Ð°Ð·Ñ€ÐµÑˆÐµÐ½ Ð´Ð»Ñ� PreparedStatement; Ð¸Ñ�Ð¿Ð¾Ð»ÑŒÐ·ÑƒÐ¹Ñ‚Ðµ Statement.
This method is not allowed for a prepared statement; use a regular statement instead. [90130-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:279)
	at homeworks.task1.Functionality.delete(WorkWithTable.java:86)
	at homeworks.task1.Main.main(Main.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
2016-05-05 21:21:38 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ð¡Ð¸Ð½Ñ‚Ð°ÐºÑ�Ð¸Ñ‡ÐµÑ�ÐºÐ°Ñ� Ð¾ÑˆÐ¸Ð±ÐºÐ° Ð² Ð²Ñ‹Ñ€Ð°Ð¶ÐµÐ½Ð¸Ð¸ SQL "DELETE FROM USERS WHERE ID = [*]"; Ð¾Ð¶Ð¸Ð´Ð°Ð»Ð¾Ñ�ÑŒ "ALL, ANY, SOME"
Syntax error in SQL statement "DELETE FROM USERS WHERE ID = [*]"; expected "ALL, ANY, SOME"; SQL statement:
DELETE from USERS WHERE ID = [42001-191]
2016-05-05 21:22:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ð”Ð°Ð½Ð½Ñ‹Ð¹ Ð¼ÐµÑ‚Ð¾Ð´ Ð½Ðµ Ñ€Ð°Ð·Ñ€ÐµÑˆÐµÐ½ Ð´Ð»Ñ� PreparedStatement; Ð¸Ñ�Ð¿Ð¾Ð»ÑŒÐ·ÑƒÐ¹Ñ‚Ðµ Statement.
This method is not allowed for a prepared statement; use a regular statement instead. [90130-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:279)
	at homeworks.task1.Functionality.delete(WorkWithTable.java:86)
	at homeworks.task1.Main.main(Main.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
2016-05-05 21:27:13 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ð”Ð°Ð½Ð½Ñ‹Ð¹ Ð¼ÐµÑ‚Ð¾Ð´ Ð½Ðµ Ñ€Ð°Ð·Ñ€ÐµÑˆÐµÐ½ Ð´Ð»Ñ� PreparedStatement; Ð¸Ñ�Ð¿Ð¾Ð»ÑŒÐ·ÑƒÐ¹Ñ‚Ðµ Statement.
This method is not allowed for a prepared statement; use a regular statement instead. [90130-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:279)
	at homeworks.task1.Functionality.update(WorkWithTable.java:74)
	at homeworks.task1.Main.main(Main.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
2016-05-05 21:29:01 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ð”Ð°Ð½Ð½Ñ‹Ð¹ Ð¼ÐµÑ‚Ð¾Ð´ Ð½Ðµ Ñ€Ð°Ð·Ñ€ÐµÑˆÐµÐ½ Ð´Ð»Ñ� PreparedStatement; Ð¸Ñ�Ð¿Ð¾Ð»ÑŒÐ·ÑƒÐ¹Ñ‚Ðµ Statement.
This method is not allowed for a prepared statement; use a regular statement instead. [90130-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:279)
	at homeworks.task1.Functionality.update(WorkWithTable.java:74)
	at homeworks.task1.Main.main(Main.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
2016-05-05 21:37:54 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ð”Ð°Ð½Ð½Ñ‹Ð¹ Ð¼ÐµÑ‚Ð¾Ð´ Ð½Ðµ Ñ€Ð°Ð·Ñ€ÐµÑˆÐµÐ½ Ð´Ð»Ñ� PreparedStatement; Ð¸Ñ�Ð¿Ð¾Ð»ÑŒÐ·ÑƒÐ¹Ñ‚Ðµ Statement.
This method is not allowed for a prepared statement; use a regular statement instead. [90130-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:279)
	at homeworks.task1.Functionality.update(WorkWithTable.java:74)
	at homeworks.task1.Main.main(Main.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
2016-05-05 21:51:10 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ð”Ð°Ð½Ð½Ñ‹Ð¹ Ð¼ÐµÑ‚Ð¾Ð´ Ð½Ðµ Ñ€Ð°Ð·Ñ€ÐµÑˆÐµÐ½ Ð´Ð»Ñ� PreparedStatement; Ð¸Ñ�Ð¿Ð¾Ð»ÑŒÐ·ÑƒÐ¹Ñ‚Ðµ Statement.
This method is not allowed for a prepared statement; use a regular statement instead. [90130-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:279)
	at homeworks.task1.Functionality.update(Functionality.java:74)
	at homeworks.task1.Main.main(Main.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
2016-05-05 21:51:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ð¡Ð¸Ð½Ñ‚Ð°ÐºÑ�Ð¸Ñ‡ÐµÑ�ÐºÐ°Ñ� Ð¾ÑˆÐ¸Ð±ÐºÐ° Ð² Ð²Ñ‹Ñ€Ð°Ð¶ÐµÐ½Ð¸Ð¸ SQL "DELETE FROM USERS WHERE ID = [*]"; Ð¾Ð¶Ð¸Ð´Ð°Ð»Ð¾Ñ�ÑŒ "ALL, ANY, SOME"
Syntax error in SQL statement "DELETE FROM USERS WHERE ID = [*]"; expected "ALL, ANY, SOME"; SQL statement:
DELETE from USERS WHERE ID = [42001-191]
2016-05-05 21:52:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ð”Ð°Ð½Ð½Ñ‹Ð¹ Ð¼ÐµÑ‚Ð¾Ð´ Ð½Ðµ Ñ€Ð°Ð·Ñ€ÐµÑˆÐµÐ½ Ð´Ð»Ñ� PreparedStatement; Ð¸Ñ�Ð¿Ð¾Ð»ÑŒÐ·ÑƒÐ¹Ñ‚Ðµ Statement.
This method is not allowed for a prepared statement; use a regular statement instead. [90130-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:279)
	at homeworks.task1.Functionality.delete(Functionality.java:89)
	at homeworks.task1.Main.main(Main.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
2016-05-06 09:41:47 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Savepoint Ð½Ðµ Ñ�ÑƒÑ‰ÐµÑ�Ñ‚Ð²ÑƒÐµÑ‚: "sevepoint 1"
Savepoint is invalid: "sevepoint 1"; SQL statement:
ROLLBACK TO SAVEPOINT "sevepoint 1" [90063-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.engine.Session.rollbackToSavepoint(Session.java:1051)
	at org.h2.command.dml.TransactionCommand.update(TransactionCommand.java:59)
	at org.h2.command.CommandContainer.update(CommandContainer.java:98)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcSavepoint.rollback(JdbcSavepoint.java:66)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:1037)
	at homeworks.task1.Functionality.insert(Functionality.java:59)
	at homeworks.task1.Main.main(Main.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
2016-05-06 09:44:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ð¡Ð¸Ð½Ñ‚Ð°ÐºÑ�Ð¸Ñ‡ÐµÑ�ÐºÐ°Ñ� Ð¾ÑˆÐ¸Ð±ÐºÐ° Ð² Ð²Ñ‹Ñ€Ð°Ð¶ÐµÐ½Ð¸Ð¸ SQL "SELECT FROM USERS [*]"; Ð¾Ð¶Ð¸Ð´Ð°Ð»Ð¾Ñ�ÑŒ "., (, AS, RIGHT, LEFT, FULL, INNER, JOIN, CROSS, NATURAL, ,, SELECT"
Syntax error in SQL statement "SELECT FROM USERS [*]"; expected "., (, AS, RIGHT, LEFT, FULL, INNER, JOIN, CROSS, NATURAL, ,, SELECT"; SQL statement:
select from USERS [42001-191]
2016-05-06 09:45:33 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ð¡Ð¸Ð½Ñ‚Ð°ÐºÑ�Ð¸Ñ‡ÐµÑ�ÐºÐ°Ñ� Ð¾ÑˆÐ¸Ð±ÐºÐ° Ð² Ð²Ñ‹Ñ€Ð°Ð¶ÐµÐ½Ð¸Ð¸ SQL "DELETE FROM USERS WHERE ID =11?[*] "
Syntax error in SQL statement "DELETE FROM USERS WHERE ID =11?[*] "; SQL statement:
DELETE from USERS WHERE ID =11? [42000-191]
2016-05-06 09:48:28 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ð¡Ð¸Ð½Ñ‚Ð°ÐºÑ�Ð¸Ñ‡ÐµÑ�ÐºÐ°Ñ� Ð¾ÑˆÐ¸Ð±ÐºÐ° Ð² Ð²Ñ‹Ñ€Ð°Ð¶ÐµÐ½Ð¸Ð¸ SQL "INSERT INTO USERS (LASTNAME, FIRSTNAME, EMAIL, PASSWORD) VALUES (? ?[*] ? ?)"; Ð¾Ð¶Ð¸Ð´Ð°Ð»Ð¾Ñ�ÑŒ "[, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, REGEXP, IS, IN, BETWEEN, AND, OR, ,, )"
Syntax error in SQL statement "INSERT INTO USERS (LASTNAME, FIRSTNAME, EMAIL, PASSWORD) VALUES (? ?[*] ? ?)"; expected "[, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, REGEXP, IS, IN, BETWEEN, AND, OR, ,, )"; SQL statement:
INSERT INTO USERS (LASTNAME, FIRSTNAME, EMAIL, PASSWORD) VALUES (? ? ? ?) [42001-191]
2016-05-06 09:59:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ð¡Ð¸Ð½Ñ‚Ð°ÐºÑ�Ð¸Ñ‡ÐµÑ�ÐºÐ°Ñ� Ð¾ÑˆÐ¸Ð±ÐºÐ° Ð² Ð²Ñ‹Ñ€Ð°Ð¶ÐµÐ½Ð¸Ð¸ SQL "INSERT INTO USERS (LASTNAME, FIRSTNAME, EMAIL, PASSWORD) VALUES (? ?[*] ? ?)"; Ð¾Ð¶Ð¸Ð´Ð°Ð»Ð¾Ñ�ÑŒ "[, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, REGEXP, IS, IN, BETWEEN, AND, OR, ,, )"
Syntax error in SQL statement "INSERT INTO USERS (LASTNAME, FIRSTNAME, EMAIL, PASSWORD) VALUES (? ?[*] ? ?)"; expected "[, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, REGEXP, IS, IN, BETWEEN, AND, OR, ,, )"; SQL statement:
INSERT INTO USERS (LASTNAME, FIRSTNAME, EMAIL, PASSWORD) VALUES (? ? ? ?) [42001-191]
2016-05-06 13:49:47 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Savepoint Ð½Ðµ Ñ�ÑƒÑ‰ÐµÑ�Ñ‚Ð²ÑƒÐµÑ‚: "SYSTEM_SAVEPOINT_0"
Savepoint is invalid: "SYSTEM_SAVEPOINT_0"; SQL statement:
ROLLBACK TO SAVEPOINT SYSTEM_SAVEPOINT_0 [90063-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.engine.Session.rollbackToSavepoint(Session.java:1051)
	at org.h2.command.dml.TransactionCommand.update(TransactionCommand.java:59)
	at org.h2.command.CommandContainer.update(CommandContainer.java:98)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcSavepoint.rollback(JdbcSavepoint.java:66)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:1037)
	at homeworks.task1.Main.main(Main.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
2016-05-06 13:51:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Savepoint Ð½Ðµ Ñ�ÑƒÑ‰ÐµÑ�Ñ‚Ð²ÑƒÐµÑ‚: "WTF"
Savepoint is invalid: "WTF"; SQL statement:
ROLLBACK TO SAVEPOINT "WTF" [90063-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.engine.Session.rollbackToSavepoint(Session.java:1051)
	at org.h2.command.dml.TransactionCommand.update(TransactionCommand.java:59)
	at org.h2.command.CommandContainer.update(CommandContainer.java:98)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcSavepoint.rollback(JdbcSavepoint.java:66)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:1037)
	at homeworks.task1.Main.main(Main.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
2016-05-06 13:53:33 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Savepoint Ð½Ðµ Ñ�ÑƒÑ‰ÐµÑ�Ñ‚Ð²ÑƒÐµÑ‚: "WTF"
Savepoint is invalid: "WTF"; SQL statement:
ROLLBACK TO SAVEPOINT "WTF" [90063-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.engine.Session.rollbackToSavepoint(Session.java:1051)
	at org.h2.command.dml.TransactionCommand.update(TransactionCommand.java:59)
	at org.h2.command.CommandContainer.update(CommandContainer.java:98)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcSavepoint.rollback(JdbcSavepoint.java:66)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:1037)
	at homeworks.task1.Main.main(Main.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
2016-05-06 13:55:28 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Savepoint Ð½Ðµ Ñ�ÑƒÑ‰ÐµÑ�Ñ‚Ð²ÑƒÐµÑ‚: "WTF"
Savepoint is invalid: "WTF"; SQL statement:
ROLLBACK TO SAVEPOINT "WTF" [90063-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.engine.Session.rollbackToSavepoint(Session.java:1051)
	at org.h2.command.dml.TransactionCommand.update(TransactionCommand.java:59)
	at org.h2.command.CommandContainer.update(CommandContainer.java:98)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcSavepoint.rollback(JdbcSavepoint.java:66)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:1037)
	at homeworks.task1.Main.main(Main.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
2016-05-06 13:57:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Savepoint Ð½Ðµ Ñ�ÑƒÑ‰ÐµÑ�Ñ‚Ð²ÑƒÐµÑ‚: "WTF"
Savepoint is invalid: "WTF"; SQL statement:
ROLLBACK TO SAVEPOINT "WTF" [90063-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.engine.Session.rollbackToSavepoint(Session.java:1051)
	at org.h2.command.dml.TransactionCommand.update(TransactionCommand.java:59)
	at org.h2.command.CommandContainer.update(CommandContainer.java:98)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcSavepoint.rollback(JdbcSavepoint.java:66)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:1037)
	at homeworks.task1.Main.main(Main.java:27)
2016-05-06 13:58:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Savepoint Ð½Ðµ Ñ�ÑƒÑ‰ÐµÑ�Ñ‚Ð²ÑƒÐµÑ‚: "WTF"
Savepoint is invalid: "WTF"; SQL statement:
ROLLBACK TO SAVEPOINT "WTF" [90063-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.engine.Session.rollbackToSavepoint(Session.java:1055)
	at org.h2.command.dml.TransactionCommand.update(TransactionCommand.java:59)
	at org.h2.command.CommandContainer.update(CommandContainer.java:98)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcSavepoint.rollback(JdbcSavepoint.java:66)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:1037)
	at homeworks.task1.Main.main(Main.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
2016-05-06 13:59:11 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Savepoint Ð½Ðµ Ñ�ÑƒÑ‰ÐµÑ�Ñ‚Ð²ÑƒÐµÑ‚: "WTF1"
Savepoint is invalid: "WTF1"; SQL statement:
ROLLBACK TO SAVEPOINT "WTF1" [90063-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.engine.Session.rollbackToSavepoint(Session.java:1051)
	at org.h2.command.dml.TransactionCommand.update(TransactionCommand.java:59)
	at org.h2.command.CommandContainer.update(CommandContainer.java:98)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcSavepoint.rollback(JdbcSavepoint.java:66)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:1037)
	at homeworks.task1.Main.main(Main.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
